name: flex_buddy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  google_fonts: ^6.2.1
  persistent_bottom_nav_bar: ^6.2.1
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  sqflite: ^2.4.1
  buttons_tabbar: ^1.3.15
  intl: ^0.20.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.1
  fl_chart: ^0.70.2
  weekly_date_picker: ^1.4.2
  random_avatar: ^0.0.8
  numberpicker: ^2.1.2
  muscle_selector: ^1.0.3
  flutter_ruler_picker: ^1.0.6
  flutter_onboarding_slider: ^1.0.11
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/exercise_body/
    - assets/images/exercise_gif/
    - assets/images/exercise_gif/GIF/
    - assets/svg/
